### PR TITLE
[fix] allow whitespace characters

### LINKED ISSUE #37: Windows binary operator error
I'm getting the following error on Windows when I try to use this package:

`.git/hooks/pre-commit: line 11: [: /c/Program: binary operator expected
pre-commit:`

This is line 11 from the referenced file:

`if [ -z $HAS_NODE ] && [ -f ~/.bash_profile ]; then`

Can you provide any help?

Package version `1.0.10`
Node version: `0.10.31`
NPM version `2.13.2`
Windows 7

### PR DESCRIPTION
**Pull request by Swaagie**
fixes #37

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
LGTM.

**Comment by jpodwys** [comment]
Thanks for the great work, guys! Looking forward to an npm release with this merge!

**Comment by 3rd-Eden** [comment]
@jpodwys Working on it, just trying to resolve some more minor issues before we release a new `1.1.0`

**Comment by jpodwys** [comment]
OK thanks for the update!

**Comment by jpodwys** [comment]
Any news on a potential release date?

**Comment by 3rd-Eden** [comment]
@jpodwys It should be fixed in the latest version which got released to npm.

**Comment by jpodwys** [comment]
Oh perfect thank you.

**Pull request merged**
