### PR TITLE
Gracefully fail on Windows.

### PR DESCRIPTION
**Pull request by indexzero**
I've seen this module be enough of a problem on Windows that I feel we need to either:

1. Fix it so that it works in a cross-platform way
2. Disable it on Windows and fail gracefully.

This pull-request does (2).

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
@indexzero: It would be nice know _what_ the actual problems are before I disable it completely. As most of these bugs can probably be fixed relatively easily

**Comment by indexzero** [comment]
@3rd-Eden bash does not exist on Windows: https://github.com/observing/pre-commit/blob/master/hook

**Comment by 3rd-Eden** [comment]
@indexzero it's easy enough to replace that with a bat file during the installation phase. https://github.com/observing/pre-commit/blob/master/install.js#L20

**Comment by indexzero** [comment]
@3rd-Eden absolutely. I know nothing about batch scripts so I thought disabling it for now was the best bet.

**Comment by Swaagie** [comment]
There are some more issue on windows in general though, might be good to fix those all at once ;)

**Comment by 3rd-Eden** [comment]
@Swaagie so you're suggesting installing linux when installing this module ;-)?

**Comment by Swaagie** [comment]
haha

**Comment by 3rd-Eden** [comment]
Fixed in #41 with a more graceful solution.

**Pull request closed without merging**
