### PR TITLE
Added quotes to allow spaces in directory names

### PR DESCRIPTION
**Pull request by jltalens**
I honestly didn't know how to cover this guy with tests further that just trying locally, any idea will be welcome.

### CODE REVIEW

**Comment by fhemberger** [comment]
@3rd-Eden Any chance to get this merged? Would be super-awesome.

**Comment by 3rd-Eden** [comment]
Sorry! I thought I already hit the merge button on this!

**Comment by 3rd-Eden** [comment]
Thanks for the contribution <3 truly appreciate it <3

**Comment by fhemberger** [comment]
Great, thank you!

**Pull request merged**
