### PR TITLE
Add ability to find .git folder on upper levels

### PR DESCRIPTION
**Pull request by Alex-Sokolov**
After make this work found that is the same as in https://github.com/observing/pre-commit/pull/55
But without adding new dependencies 😄

### CODE REVIEW

**Comment by sreichi** [comment]
will this be merged soon? really looking forward to this

**Comment by Alex-Sokolov** [comment]
@sreichi while waiting you can try https://github.com/typicode/husky

**Comment by sreichi** [comment]
@Alex-Sokolov thanks a lot worked out of the box 👍

**Comment by 3rd-Eden** [comment]
ty <3

**Comment by Pterrat** [comment]
Thank you so much

**Comment by saschanaz** [comment]
Looks like this feature hasn't been published yet?

**Pull request merged**
